config/routes.rb
Akera::Application.routes.draw do
  root "home#index"

  resources :albums, :only => [:index, :show]

end

app/models/item.rb
class Item < ActiveRecord::Base
  def self.albums
    app = FbGraph::Application.new(300450546746887, :secret => '71e6e5ab681e76090a2da7065905bb7a')
    token = app.get_access_token
    page = FbGraph::Page.fetch('byakera', :access_token => token)
    # debugger
    page.albums.map{ |a| a if a.name.match('A K E R A') != nil }.compact!
  end

  # def photos
  #   self.photos(:limit => 200)
  # end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = @page.albums.map{ |a| a if a.name.match('A K E R A') != nil }.compact!
    
  end

  def show
    @album = @page.albums.map{|x| x if x.identifier == "#{params[:id]}"}.compact![0]
    @photos = @album.photos(:limit => 200)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate

  def authenticate
    app = FbGraph::Application.new(300450546746887, :secret => '71e6e5ab681e76090a2da7065905bb7a')
    @token = app.get_access_token
    @page = FbGraph::Page.fetch('byakera', :access_token => @token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @albums = Item.albums
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/show.html.erb
<div class="gallery">
  <h2 class="title"><%= @album.name %></h2>
  <div class="row item-detail">
    <div class="col-sm-6 item-image">
      <%= image_tag(@photos.first.images.first.source , class: "img-responsive") %>
    </div>
    <div class="col-sm-6 item-description">
      <h5>Detail</h5>
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto</p>
    </div>
    <div class="close-item-detail">
      <a href="#">CLOSE</a>
    </div>
  </div>
  <ul id="gallery">
    <% @photos.each do |photo| %>
      <li>
        <div class="item photo">
          <div>
            <%= image_tag(photo.images.first.source , class: "img-responsive") %>
            <p class="photo-name hidden">
              <%= photo.name %>
            </p>
          </div>
        </div>
      </li>
   <% end %>
  </ul>
</div>

app/views/home/index.html.erb
<h2 class="title">Collection</h2>
<ul id="gallery">
  <% @albums.each do |album| %>
    <li>
      <div class="item">
        <div>
          <% if album.photos.present? %>
          <%= link_to image_tag(album.photos.first.images.first.source , class: "img-responsive"), album_path(id: album.identifier) %>
          <% end %>
          <h5><%= album.name %></h5>
        </div>
      </div>
    </li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akera</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
      <div class="text-center brand">
        <h1><%= link_to "AKERA", root_path %></h1>
      </div>
      <nav id="menu">
        <ul id="menu-nav">
          <li class=""><a href="/#collection">Collection</a></li>
          <li class="current"><a href="#about">About</a></li>
          <li class=""><a href="#contact">Contact</a></li>
        </ul>
      </nav>
  </div>
  <div class="container main">
    <div class="wrap">
      <div class="row white">
        <%= render "shared/banner" %>
      </div>
      <div class="row" id="collection">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
      <div class="row white" id="about">
        <div class="col-sm-12">
          <h2 class="title">About</h2>
          <p>
            <%= @page.raw_attributes[:about ]%>
          </p>
        </div>
      </div>
      <div class="row" id="contact">
        <div class="col-sm-12">
          <h2 class="title">Contact</h2>
          <p>
            <%= @page.raw_attributes[:website ]%>
          </p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/shared/_banner.html.erb
<ul class="banner">
  <% 3.times do %>
    <li><%= image_tag("https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-prn2/c0.126.851.315/p851x315/1379382_530562207012518_1627329594_n.jpg")%></li>
  <% end %>
</ul>